on:
  push:
    tags:
      - "v*"

name: Docker Publish

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build latest
        run: docker build -t packetframe/docker-unbound-dns64:latest .
      - name: Push latest
        run: docker push packetframe/docker-unbound-dns64:latest
